- filename: DBLP.bib
  search_type: FEED
  source_name: European Confereence on Information Systems
  source_url: ''
  search_parameters: 
    - endpoint: dblp
      params: SCOPE venue_key='conf/ecis' AND journal_abbreviated='ecis'
  comment: ''
- filename: pdfs.bib
  search_type: FEED
  source_name: ECIS
  source_url: pdfs
  search_parameters:
  - endpoint: pdfs_directory
    params: SCOPE path='pdfs' WITH conference='European Conference on Information Systems' AND sub_dir_pattern='year'
  comment: NA
